// packages/template-master-detail-ng/src/app/cars/car-list.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core'
import { RouterExtensions } from '@nativescript/angular'
import { ListViewEventData } from 'nativescript-ui-listview'
import { Subscription } from 'rxjs'
import { finalize } from 'rxjs/operators'
import { ObservableArray } from '@nativescript/core'

import { Car } from './shared/car.model'
import { CarService } from './shared/car.service'

@Component({
    selector: 'CarsList',
    templateUrl: './car-list.component.html',
    styleUrls: ['./car-list.component.scss'],
})
export class CarListComponent implements OnInit, OnDestroy {
    private _isLoading: boolean = false
    private _cars: ObservableArray<Car> = new ObservableArray<Car>([])
    private _dataSubscription: Subscription

    constructor(
        private _carService: CarService,
        private _routerExtensions: RouterExtensions
    ) {}

    ngOnInit(): void {
        if (!this._dataSubscription) {
            this._isLoading = true

            this._dataSubscription = this._carService
                .load()
                .pipe(finalize(() => (this._isLoading = false)))
                .subscribe((cars: Array<Car>) => {
                    this._cars = new ObservableArray(cars)
                    this._isLoading = false
                })
        }
    }

    ngOnDestroy(): void {
        if (this._dataSubscription) {
            this._dataSubscription.unsubscribe()
            this._dataSubscription = null
        }
    }

    get cars(): ObservableArray<Car> {
        return this._cars
    }

    get isLoading(): boolean {
        return this._isLoading
    }

    onCarItemTap(args: ListViewEventData): void {
        const tappedCarItem = args.view.bindingContext

        this._routerExtensions.navigate(
            ['/cars/car-detail', tappedCarItem.id],
            {
                animated: true,
                transition: {
                    name: 'slide',
                    duration: 200,
                    curve: 'ease',
                },
            }
        )
    }
}

<ActionBar>
  <!-- Should remove the navigation button -->
  <NavigationButton ios:visibility="collapsed"></NavigationButton>
  <Label text="Browse" horizontalAlignment="center"></Label>
</ActionBar>

<GridLayout>
  <RadListView
    [items]="cars"
    (itemTap)="onCarItemTap($event)"
    class="cars-list"
  >
    <!--
    RadListView is a UI component part of the Progress NativeScript UI set of components.
    Learn more about the RadListView UI component and how it can be customized in this documentation article:
    https://docs.nativescript.org/angular/ui/professional-ui-components/ng-ListView/getting-started
    This component is used to display the master list in the master-detail structure.
    -->
    <ng-template tkListItemTemplate let-car="item">
      <StackLayout class="cars-list__item">
        <GridLayout
          rows="*, *, *"
          columns="*, *"
          class="cars-list__item-content"
        >
          <Label
            [text]="car.name"
            class="cars-list__item-name font-weight-bold"
          ></Label>
          <Label col="1" horizontalAlignment="right" class="m-r-5">
            <FormattedString>
              <Span text="&euro;"></Span>
              <Span [text]="car.price"></Span>
              <Span text="/day"></Span>
            </FormattedString>
          </Label>

          <StackLayout row="1" class="hr m-y-5" colSpan="2"></StackLayout>

          <Image
            row="2"
            [src]="car.imageUrl"
            stretch="aspectFill"
            height="120"
            class="m-r-20"
          ></Image>
          <StackLayout row="2" col="1" verticalAlignment="center">
            <Label class="p-b-10">
              <!-- set fontFamily="system" to workaround "Service exited due to Segmentation fault: 11" error -->
              <FormattedString ios:fontFamily="system">
                <Span
                  text="&#xf1b9;    "
                  class="fas cars-list__item-icon"
                ></Span>
                <Span [text]="car.class"></Span>
              </FormattedString>
            </Label>
            <Label class="p-b-10">
              <!-- set fontFamily="system" to workaround "Service exited due to Segmentation fault: 11" error -->
              <FormattedString ios:fontFamily="system">
                <Span
                  text="&#xf085;   "
                  class="fas cars-list__item-icon"
                ></Span>
                <Span [text]="car.transmission"></Span>
                <Span text=" Transmission"></Span>
              </FormattedString>
            </Label>
            <Label>
              <!-- set fontFamily="system" to workaround "Service exited due to Segmentation fault: 11" error -->
              <FormattedString ios:fontFamily="system">
                <Span
                  text="&#xf2dc;    "
                  class="fas cars-list__item-icon"
                ></Span>
                <Span [text]="car.hasAC ? 'Yes' : 'No'"></Span>
              </FormattedString>
            </Label>
          </StackLayout>
        </GridLayout>
      </StackLayout>
    </ng-template>
  </RadListView>

  <ActivityIndicator [busy]="isLoading"></ActivityIndicator>
</GridLayout>

// packages/template-master-detail-vue/app/components/CarList.vue
<template>
    <Page>
        <ActionBar>
            <Label horizontalAlignment="center" text="Car List"/>
        </ActionBar>

        <RadListView @itemTap="onItemTap" class="cars-list" for="item in cars" v-if="!isLoading">
            <ListViewLinearLayout scrollDirection="Vertical" v-tkListViewLayout/>
            <v-template>
                <StackLayout class="cars-list__item">
                    <GridLayout class="cars-list__item-content" columns="*, *" rows="*, *, *">
                        <Label :text="item.name" class="cars-list__item-name font-weight-bold"/>
                        <Label class="m-r-5" col="1" horizontalAlignment="right">
                            <FormattedString>
                                <Span text.decode="&euro;"/>
                                <Span :text="item.price"/>
                                <Span text="/day"/>
                            </FormattedString>
                        </Label>

                        <Label class="hr m-y-5" colSpan="2" row="1"/>

                        <Image :src="item.imageUrl" class="m-r-20" height="120" loadMode="async" row="2"
                               stretch="aspectFill"/>

                        <StackLayout col="1" row="2" verticalAlignment="center">
                            <Label class="p-b-10">
                                <FormattedString ios.fontFamily="system">
                                    <Span class="fas cars-list__item-icon" text.decode="&#xf1b9;    "></Span>
                                    <Span :text="item.class"/>
                                </FormattedString>
                            </Label>
                            <Label class="p-b-10">
                                <FormattedString ios.fontFamily="system">
                                    <Span class="fas cars-list__item-icon" text.decode="&#xf085;   "/>
                                    <Span :text="item.transmission"/>
                                    <Span text=" Transmission"/>
                                </FormattedString>
                            </Label>
                            <Label class="p-b-10">
                                <FormattedString ios.fontFamily="system">
                                    <Span class="fas cars-list__item-icon" text.decode="&#xf2dc;    "/>
                                    <Span :text="item.hasAC ? 'Yes' : 'No'"/>
                                </FormattedString>
                            </Label>
                        </StackLayout>
                    </GridLayout>
                </StackLayout>
            </v-template>
        </RadListView>
        <ActivityIndicator :busy="isLoading" v-else/>
    </Page>
</template>

<script>
  import CarDetails from "./CarDetails";

  export default {
    props: {
      cars: Array
    },

    computed: {
      isLoading() {
        return !this.cars.length;
      }
    },

    methods: {
      onItemTap(args) {
        this.$emit("select", args.item);
        this.$navigateTo(CarDetails, {props: {car: args.item}});
      }
    }
  };
</script>

<style lang="scss" scoped>
    @import '@nativescript/theme/scss/variables/blue';

    // Custom styles
    .cars-list {
        &__item {
            padding: 0 0 8 0;
            @include colorize($background-color: background-alt-10);

            &-content {
                padding: 8 15 4 15;
                @include colorize($background-color: background);
            }

            &-name,
            &-icon {
                @include colorize($contrasted-color: complementary background 30% 0%);
            }
        }
    }
</style>
