// packages/template-master-detail-vue/app/components/CarList.vue
<template>
    <Page>
        <ActionBar>
            <Label horizontalAlignment="center" text="Car List"/>
        </ActionBar>

        <RadListView @itemTap="onItemTap" class="cars-list" for="item in cars" v-if="!isLoading">
            <ListViewLinearLayout scrollDirection="Vertical" v-tkListViewLayout/>
            <v-template>
                <StackLayout class="cars-list__item">
                    <GridLayout class="cars-list__item-content" columns="*, *" rows="*, *, *">
                        <Label :text="item.name" class="cars-list__item-name font-weight-bold"/>
                        <Label class="m-r-5" col="1" horizontalAlignment="right">
                            <FormattedString>
                                <Span text.decode="&euro;"/>
                                <Span :text="item.price"/>
                                <Span text="/day"/>
                            </FormattedString>
                        </Label>

                        <Label class="hr m-y-5" colSpan="2" row="1"/>

                        <Image :src="item.imageUrl" class="m-r-20" height="120" loadMode="async" row="2"
                               stretch="aspectFill"/>

                        <StackLayout col="1" row="2" verticalAlignment="center">
                            <Label class="p-b-10">
                                <FormattedString ios.fontFamily="system">
                                    <Span class="fas cars-list__item-icon" text.decode="&#xf1b9;    "></Span>
                                    <Span :text="item.class"/>
                                </FormattedString>
                            </Label>
                            <Label class="p-b-10">
                                <FormattedString ios.fontFamily="system">
                                    <Span class="fas cars-list__item-icon" text.decode="&#xf085;   "/>
                                    <Span :text="item.transmission"/>
                                    <Span text=" Transmission"/>
                                </FormattedString>
                            </Label>
                            <Label class="p-b-10">
                                <FormattedString ios.fontFamily="system">
                                    <Span class="fas cars-list__item-icon" text.decode="&#xf2dc;    "/>
                                    <Span :text="item.hasAC ? 'Yes' : 'No'"/>
                                </FormattedString>
                            </Label>
                        </StackLayout>
                    </GridLayout>
                </StackLayout>
            </v-template>
        </RadListView>
        <ActivityIndicator :busy="isLoading" v-else/>
    </Page>
</template>

<script>
  import CarDetails from "./CarDetails";

  export default {
    props: {
      cars: Array
    },

    computed: {
      isLoading() {
        return !this.cars.length;
      }
    },

    methods: {
      onItemTap(args) {
        this.$emit("select", args.item);
        this.$navigateTo(CarDetails, {props: {car: args.item}});
      }
    }
  };
</script>

<style lang="scss" scoped>
    @import '@nativescript/theme/scss/variables/blue';

    // Custom styles
    .cars-list {
        &__item {
            padding: 0 0 8 0;
            @include colorize($background-color: background-alt-10);

            &-content {
                padding: 8 15 4 15;
                @include colorize($background-color: background);
            }

            &-name,
            &-icon {
                @include colorize($contrasted-color: complementary background 30% 0%);
            }
        }
    }
</style>

// packages/template-master-detail-ng/app/cars/car-list.component.ts
import { Component, OnInit } from "@angular/core";
import { ObservableArray } from "data/observable-array";
import { RouterExtensions } from "nativescript-angular/router";

import { Car } from "./shared/car.model";
import { CarService } from "./shared/car.service";

@Component({
    selector: "CarsList",
    moduleId: module.id,
    templateUrl: "./car-list.component.html"
})
export class CarListComponent implements OnInit {
    private _isLoading: boolean;
    private _cars: ObservableArray<Car>;

    constructor(
        private _carService: CarService,
        private _routerExtensions: RouterExtensions
    ) {
        // Initialize default values.
        this._cars = new ObservableArray<Car>([]);
        this._isLoading = false;
    }

    ngOnInit(): void {
        this._isLoading = true;

        this._carService.load()
            .finally(() => this._isLoading = false)
            .subscribe((cars: Array<Car>) => {
                this._cars = new ObservableArray(cars);
                this._isLoading = false;
            });
    }

    get cars(): ObservableArray<Car> {
        return this._cars;
    }

    get isLoading(): boolean {
        return this._isLoading;
    }

    onCarItemTap(args): void {
        const tappedCarItem = args.object.bindingContext;

        this._routerExtensions.navigate(["/car-detail", tappedCarItem.id]);
    }
}

<ActionBar title="Browse" icon="">
</ActionBar>

<GridLayout>
    <RadListView [items]="cars" (itemTap)="onCarItemTap($event)">
        <ng-template tkListItemTemplate let-car="item">
            <StackLayout>
                <GridLayout rows="*, 3*" columns="*, *">
                    <Label [text]="car.name"></Label>
                    <Label col="1" horizontalAlignment="right">
                        <FormattedString>
                            <Span text="€"></Span>
                            <Span [text]="car.price"></Span>
                            <Span text="/day"></Span>
                        </FormattedString>
                    </Label>
                    <Image row="1" [src]="car.imageUrl"></Image>
                    <StackLayout row="1" col="1" verticalAlignment="center">
                        <Label>
                            <FormattedString>
                                <Span text="&#xf1b9; " class="fa"></Span>
                                <Span [text]="car.class"></Span>
                            </FormattedString>
                        </Label>
                        <Label>
                            <FormattedString>
                                <Span text="&#xf085; " class="fa"></Span>
                                <Span [text]="car.transmission"></Span>
                                <Span text=" Transmission"></Span>
                            </FormattedString>
                        </Label>
                        <Label>
                            <FormattedString>
                                <Span text="&#xf2dc; " class="fa"></Span>
                                <Span [text]="car.hasAC ? 'Yes' : 'No'"></Span>
                            </FormattedString>
                        </Label>
                    </StackLayout>
                </GridLayout>
            </StackLayout>
        </ng-template>
    </RadListView>

    <ActivityIndicator [busy]="isLoading"></ActivityIndicator>
</GridLayout>
