// packages/template-drawer-navigation-vue/app/components/Featured.vue
<template>
    <Page class="page">
        <ActionBar class="action-bar">
            <!--
            Use the NavigationButton as a side-drawer button in Android
            because ActionItems are shown on the right side of the ActionBar
            -->
            <NavigationButton ios:visibility="collapsed" @tap="onDrawerButtonTap">
              <Label class="fas" text.decode="&#xf0c9;"></Label>
            </NavigationButton>
            <!--
            Use the ActionItem for IOS with position set to left. Using the
            NavigationButton as a side-drawer button in iOS is not possible,
            because its function is to always navigate back in the application.
            -->
            <ActionItem android:visibility="collapsed"
                        @tap="onDrawerButtonTap"
                        ios.position="left">
              <Label class="fas" text.decode="&#xf0c9;"></Label>
            </ActionItem>
            <Label class="action-bar-title" text="Featured"/>
        </ActionBar>

        <GridLayout class="page__content">
            <Label class="page__content-icon fas" text.decode="&#xf005;"/>
            <Label class="page__content-placeholder" :text="message"/>
        </GridLayout>
    </Page>
</template>

<script>
  import * as utils from "~/shared/utils";
  import { SelectedPageService } from "../shared/selected-page-service";

  export default {
    mounted() {
      SelectedPageService.getInstance().updateSelectedPage("Featured");
    },
    computed: {
      message() {
        return "<!-- Page content goes here -->";
      }
    },
    methods: {
      onDrawerButtonTap() {
        utils.showDrawer();
      }
    }
  };
</script>

<style scoped lang="scss">
    // Start custom common variables
    @import '@nativescript/theme/scss/variables/blue';
    // End custom common variables

    // Custom styles
</style>

// packages/template-drawer-navigation-ng/src/app/featured/featured.component.ts
import { Component, OnInit } from '@angular/core'
import { RadSideDrawer } from 'nativescript-ui-sidedrawer'
import { Application } from '@nativescript/core'

@Component({
    selector: 'Featured',
    templateUrl: './featured.component.html',
})
export class FeaturedComponent implements OnInit {
    constructor() {
        // Use the component constructor to inject providers.
    }

    ngOnInit(): void {
        // Init your component properties here.
    }

    onDrawerButtonTap(): void {
        const sideDrawer = <RadSideDrawer>Application.getRootView()
        sideDrawer.showDrawer()
    }
}

<ActionBar>
  <!--
    Use the NavigationButton as a side-drawer button in Android
    because ActionItems are shown on the right side of the ActionBar
    -->
  <NavigationButton
    ios:visibility="collapsed"
    (tap)="onDrawerButtonTap()"
  >
    <Label class="fas" text="&#xf0c9;"></Label>
  </NavigationButton>
  <!--
    Use the ActionItem for IOS with position set to left. Using the
    NavigationButton as a side-drawer button in iOS is not possible,
    because its function is to always navigate back in the application.
    -->
  <ActionItem
    android:visibility="collapsed"
    (tap)="onDrawerButtonTap()"
    ios.position="left"
  >
    <Label class="fas" text="&#xf0c9;"></Label>
  </ActionItem>
  <Label text="Featured"></Label>
</ActionBar>

<GridLayout class="page__content">
  <Label class="page__content-icon fas" text="&#xf005;"></Label>
  <Label class="page__content-placeholder" text="<!-- Page content goes here -->"></Label>
</GridLayout>
