// packages/template-tab-navigation-ng/src/app/search/search.component.ts
import { Component, OnInit } from '@angular/core'

@Component({
    selector: 'Search',
    templateUrl: './search.component.html',
})
export class SearchComponent implements OnInit {
    constructor() {
        // Use the constructor to inject services.
    }

    ngOnInit(): void {
        // Use the "ngOnInit" handler to initialize data for the view.
    }
}

<ActionBar>
  <Label text="Search"></Label>
</ActionBar>

<GridLayout class="page__content">
  <Label class="page__content-icon fas" text="&#xf002;"></Label>
  <Label
    class="page__content-placeholder"
    text="<!-- Search page content goes here -->"
  ></Label>
</GridLayout>

// packages/template-tab-navigation-vue/src/components/Search.vue
<template lang="html">
    <Page>
        <ActionBar>
            <Label text="Search"></Label>
        </ActionBar>

        <GridLayout class="page__content">
            <Label class="page__content-icon fas" text.decode="&#xf002;"></Label>
            <Label class="page__content-placeholder" :text="message"></Label>
        </GridLayout>
    </Page>
</template>

<script>
  export default {
    data() {
      return {
        message: "<!-- Search page content goes here -->"
      };
    }
  }
</script>

<style lang="scss" scoped>
    // Start custom common variables
    @import "~@nativescript/theme/scss/variables/blue";
    // End custom common variables

    // Custom styles

</style>
