// packages/template-blank-svelte-vision/src/components/Home.svelte
<page>
    <actionBar title="Home" />
    <gridLayout>
        <label class="info">
            <formattedString>
                <span class="fas" text="&#xf135;" />
                <span text=" {message}" />
            </formattedString>
        </label>
    </gridLayout>
</page>

<script lang="ts">
    let message: string = "Blank Svelte Native App"
</script>

<style>
    .info .fas {
        color: #3A53FF;
    }

    .info {
        font-size: 25;
        horizontal-align: center;
        vertical-align: center;
    }
</style>

// packages/template-blank-solid-ts/app/components/home.tsx
import { useRoute } from 'solid-navigation';

export default function Home() {
  const route = useRoute();
  const message = 'Blank SolidJS App'

  return (
    <>
      <actionbar title={route.name} />
      <gridlayout>
        <label
          style={{
            fontSize: 20,
            horizontalAlignment: 'center',
            verticalAlignment: 'middle',
          }}
        >
          <formattedstring>
            <span
              className="fas"
              text={String.fromCharCode(0xf135)}
              style={{
                color: '#3A53FF',
              }}
            />
            <span text={` ${message}`} />
          </formattedstring>
        </label>
      </gridlayout>
    </>
  )
}
