// packages/template-tab-navigation-vue/app/components/App.vue
<template lang="html">
    <BottomNavigation>
        <TabStrip>
            <TabStripItem>
                <Label text="Home"></Label>
                <Image src.decode="font://&#xf015;" class="fa t-36"></Image>
            </TabStripItem>
            <TabStripItem>
                <Label text="Browse"></Label>
                <Image src.decode="font://&#xf1ea;" class="fa t-36"></Image>
            </TabStripItem>
            <TabStripItem>
                <Label text="Search"></Label>
                <Image src.decode="font://&#xf002;" class="fa t-36"></Image>
            </TabStripItem>
        </TabStrip>

        <TabContentItem>
            <Frame>
                <Items />
            </Frame>
        </TabContentItem>

        <TabContentItem>
            <Frame>
                <Browse />
            </Frame>
        </TabContentItem>

        <TabContentItem>
            <Frame>
                <Search />
            </Frame>
        </TabContentItem>

    </BottomNavigation>
</template>

<script>
import Items from "./Items.vue";
import Browse from "./Browse.vue";
import Search from "./Search.vue";

export default {
  components: {
    Items,
    Browse,
    Search
  }
};
</script>

<style lang="scss">
// Start custom common variables
@import "../app-variables";
// End custom common variables

// Custom styles

</style>

// packages/template-tab-navigation-ng/src/app/app.component.ts
import { Component, OnInit } from '@angular/core'

@Component({
    selector: 'ns-app',
    templateUrl: 'app.component.html',
})
export class AppComponent implements OnInit {
    constructor() {
        // Use the component constructor to inject providers.
    }

    ngOnInit(): void {
        // Init your component properties here.
    }
}

<BottomNavigation>
    <TabStrip>
        <!--
            Besides the approach demonstrated below there is alternative shorthand syntax for setting TabStripItem title and icon:

            <TabStripItem title="Home" iconSource="font://&#xf015;" />

            Both shorthand and verbose syntax can use
            TabStripItem Label {...} css selector to style the title label,
            and TabStriptItem Image {...} css selector to style the icon image (see _app-common.scss).
         -->
        <TabStripItem>
            <Label text="Home"></Label>
            <Image src="font://&#xf015;" class="fa"></Image>
        </TabStripItem>
        <TabStripItem>
            <Label text="Browse"></Label>
            <Image src="font://&#xf1ea;" class="fa"></Image>
        </TabStripItem>
        <TabStripItem>
            <Label text="Search"></Label>
            <Image src="font://&#xf002;" class="fa"></Image>
        </TabStripItem>
    </TabStrip>

    <TabContentItem>
        <page-router-outlet name="homeTab"></page-router-outlet>
    </TabContentItem>

    <TabContentItem>
        <page-router-outlet name="browseTab"></page-router-outlet>
    </TabContentItem>

    <TabContentItem>
        <page-router-outlet name="searchTab"></page-router-outlet>
    </TabContentItem>
</BottomNavigation>
